### ISSUE TITLE
Error: Status Code: 404

### ISSUE THREAD

**Issue by alexlee928** [kokushin/node-twatch#1]
Hello, I found the following error as required,  thank you

npm run twatch -- --u realDonaldTrump

Error: Status Code: 404
    at Request.<anonymous> (/Users/xxxxx/Desktop/WatchDog/node-twatch/node_modules/twitter/lib/twitter.js:277:28)
    at Request.emit (events.js:193:13)
    at Request.onRequestResponse (/Users/xxxxx/Desktop/WatchDog/node-twatch/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:193:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at TLSSocket.socketOnData (_http_client.js:447:22)
    at TLSSocket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)

**Comment by alexlee928** [comment]
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html
